[tool.poetry]
name = "cpp-dev"
version = "0.1.0"
description = ""
authors = ["Andi Hellmund <am.hellmund@gmail.com>"]
readme = "README.md"
packages = [{include = "cpp_dev", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
typed-argparse = "^0.3.1"

[tool.poetry.scripts]
cpd = "cpp_dev.ui.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
