exclude = ["conan"]
indent-width = 4
line-length = 120
target-version = "py312"

[lint]
ignore = [
    "COM812",
    "D100",
    "D104",
    "D105",
    "D107",
    "D203",
    "D213",
    "EM101",
    "EM102",
    "G004",
    "ISC001",
    "PLR2004",
    "TC001",
    "TRY003",
]
select = ["ALL"]

[lint.per-file-ignores]
"test_*.py" = ["D", "S101"]
