os:
  Linux:
    distro: ["Ubuntu-24.04"]   
arch: [x86_64]
compiler:
    gcc:
        version: ["13"]
        cppstd: [None, 20]
        libcxx: [libstdc++, libstdc++11]
    clang:
        version: ["19"]
        libcxx: [None, libstdc++, libstdc++11, libc++, c++_shared, c++_static]
        cppstd: [None, 20]
build_type: [None, Debug, Release, RelWithDebInfo, MinSizeRel]